# ----- < Custom > ----- #
execute if entity @s[type=minecraft:wandering_trader] if predicate reforge:25_percentage run data modify entity @s Offers.Recipes append value {rewardExp:1b,maxUses:1,uses:0,xp:5,buy:{id:"minecraft:emerald",count:30},buyB:{id:"minecraft:gold_block",count:10},sell:{id:"minecraft:player_head",count:1,components:{"minecraft:max_stack_size":16,"minecraft:custom_name":{"color":"aqua","italic":false,"text":"Block of Keyhole"},"minecraft:lore":[[{"color":"gray","italic":false,"text":"⚒ "},{"bold":true,"color":"white","italic":false,"text":"Scavenger: "},{"bold":false,"color":"gray","italic":false,"text":"Learn the way to pick up used items!"}],{"color":"gray","italic":false,"text":"10% Chance to pick up on ground projectile (Unpickable items) like mob’s arrow, trident etc..."},{"color":"gray","italic":false,"text":"Put it in the Reforge Anvil with the item to forge it!"},{"color":"gray","italic":false,"text":""},[{"color":"dark_gray","italic":false,"text":"Can apply to: "},{"bold":true,"color":"white","italic":false,"text":"Chestplate"}],{"color":"green","italic":false,"text":"Xp Level Cost: 15"}],"minecraft:unbreakable":{},"minecraft:rarity":"rare","minecraft:custom_data":{reforgeid:53,req_xp:15},"minecraft:profile":{id:[I;-2051494537,-1537588399,-1329577230,108640062],properties:[{name:"textures",signature:"23",value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZhYTdmZDdlNDlhMjJiNGRhMzY1OThkYjQ3ZTZkMDBkY2VhMzY4MWViOWM3NWM0YWM5Mzk2MjBmZTg4ODIwZCJ9fX0"}]}}}}
execute if entity @s[type=minecraft:skeleton,tag=!boss] if predicate reforge:10_percentage run function mobs:skeleton_with_sword/init_normal
execute if entity @s[type=minecraft:stray,tag=!stray_sword] if predicate reforge:10_percentage run function mobs:skeleton_with_sword/init_stray
execute if entity @s[type=minecraft:bogged,tag=!bogged_sword] if predicate reforge:10_percentage run function mobs:skeleton_with_sword/init_bogged
execute if entity @s[type=minecraft:wither_skeleton,tag=!boss] if predicate reforge:10_percentage run function mobs:wither_skeleton_ranged/init
execute if entity @s[type=minecraft:enderman,tag=!ranger_enderman] if predicate reforge:10_percentage run function mobs:ranger_enderman/init
execute if entity @s[type=minecraft:elder_guardian,tag=!superior_guardian] if predicate reforge:20_percentage run function mobs:superior_guardian/init
#execute if entity @s[type=minecraft:ender_dragon,tag=!ender_dragon] run function mobs:ender_dragon/init
# ---------------------- #