execute unless score .arrow_potion_id const matches 0.. run return fail
execute if score .arrow_potion_id const matches 0 run effect give @s glowing 10 0 false
execute if score .arrow_potion_id const matches 1 run effect give @s minecraft:speed 22 0 false
execute if score .arrow_potion_id const matches 2 run effect give @s minecraft:speed 11 1 false
execute if score .arrow_potion_id const matches 3 run effect give @s minecraft:speed 60 0 false
execute if score .arrow_potion_id const matches 4 run effect give @s minecraft:slowness 11 0 false
execute if score .arrow_potion_id const matches 5 run effect give @s minecraft:slowness 2 3 false
execute if score .arrow_potion_id const matches 6 run effect give @s minecraft:slowness 30 0 false
execute if score .arrow_potion_id const matches 7 run effect give @s minecraft:strength 22 0 false
execute if score .arrow_potion_id const matches 8 run effect give @s minecraft:strength 11 1 false
execute if score .arrow_potion_id const matches 9 run effect give @s minecraft:strength 60 0 false
execute if score .arrow_potion_id const matches 10 run effect give @s minecraft:weakness 11 0 false
execute if score .arrow_potion_id const matches 11 run effect give @s minecraft:weakness 30 0 false
execute if score .arrow_potion_id const matches 12 run effect give @s minecraft:instant_health 1 0 false
execute if score .arrow_potion_id const matches 13 run effect give @s minecraft:instant_health 1 1 false
execute if score .arrow_potion_id const matches 14 run effect give @s minecraft:instant_damage 1 0 false
execute if score .arrow_potion_id const matches 15 run effect give @s minecraft:instant_damage 1 1 false
execute if score .arrow_potion_id const matches 16 run effect give @s minecraft:jump_boost 22 0 false
execute if score .arrow_potion_id const matches 17 run effect give @s minecraft:jump_boost 11 1 false
execute if score .arrow_potion_id const matches 18 run effect give @s minecraft:jump_boost 60 0 false
execute if score .arrow_potion_id const matches 19 run effect give @s minecraft:luck 37 0 false
execute if score .arrow_potion_id const matches 20 run effect give @s minecraft:regeneration 5 0 false
execute if score .arrow_potion_id const matches 21 run effect give @s minecraft:regeneration 2 1 false
execute if score .arrow_potion_id const matches 22 run effect give @s minecraft:regeneration 11 0 false
execute if score .arrow_potion_id const matches 23 run effect give @s minecraft:poison 5 0 false
execute if score .arrow_potion_id const matches 24 run effect give @s minecraft:poison 2 1 false
execute if score .arrow_potion_id const matches 25 run effect give @s minecraft:poison 11 0 false
execute if score .arrow_potion_id const matches 26 run effect give @s minecraft:fire_resistance 22 0 false
execute if score .arrow_potion_id const matches 27 run effect give @s minecraft:fire_resistance 60 0 false
execute if score .arrow_potion_id const matches 28 run effect give @s minecraft:water_breathing 22 0 false
execute if score .arrow_potion_id const matches 29 run effect give @s minecraft:water_breathing 60 0 false
execute if score .arrow_potion_id const matches 30 run effect give @s minecraft:night_vision 22 0 false
execute if score .arrow_potion_id const matches 31 run effect give @s minecraft:night_vision 60 0 false
execute if score .arrow_potion_id const matches 32 run effect give @s minecraft:invisibility 22 0 false
execute if score .arrow_potion_id const matches 33 run effect give @s minecraft:invisibility 60 0 false
execute if score .arrow_potion_id const matches 34 run effect give @s minecraft:slowness 2 3 false
execute if score .arrow_potion_id const matches 34 run effect give @s minecraft:resistance 2 2 false
execute if score .arrow_potion_id const matches 35 run effect give @s minecraft:slowness 2 5 false
execute if score .arrow_potion_id const matches 35 run effect give @s minecraft:resistance 2 3 false
execute if score .arrow_potion_id const matches 36 run effect give @s minecraft:slowness 5 3 false
execute if score .arrow_potion_id const matches 36 run effect give @s minecraft:resistance 5 2 false
execute if score .arrow_potion_id const matches 37 run effect give @s minecraft:slow_falling 11 0 false
execute if score .arrow_potion_id const matches 38 run effect give @s minecraft:slow_falling 30 0 false
execute if score .arrow_potion_id const matches 39 run effect give @s minecraft:wind_charged 22 0 false
execute if score .arrow_potion_id const matches 40 run effect give @s minecraft:oozing 22 0 false
execute if score .arrow_potion_id const matches 41 run effect give @s minecraft:infested 22 0 false
execute if score .arrow_potion_id const matches 42 run effect give @s minecraft:weaving 22 0 false