execute if entity @s[type=minecraft:spectral_arrow] run scoreboard players set .arrow_potion_id const 0
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:swiftness"} run scoreboard players set .arrow_potion_id const 1
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_swiftness"} run scoreboard players set .arrow_potion_id const 2
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_swiftness"} run scoreboard players set .arrow_potion_id const 3
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:slowness"} run scoreboard players set .arrow_potion_id const 4
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_slowness"} run scoreboard players set .arrow_potion_id const 5
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_slowness"} run scoreboard players set .arrow_potion_id const 6
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strength"} run scoreboard players set .arrow_potion_id const 7
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_strength"} run scoreboard players set .arrow_potion_id const 8
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_strength"} run scoreboard players set .arrow_potion_id const 9
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:weakness"} run scoreboard players set .arrow_potion_id const 10
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_weakness"} run scoreboard players set .arrow_potion_id const 11
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:healing"} run scoreboard players set .arrow_potion_id const 12
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_healing"} run scoreboard players set .arrow_potion_id const 13
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:harming"} run scoreboard players set .arrow_potion_id const 14
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_harming"} run scoreboard players set .arrow_potion_id const 15
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:leaping"} run scoreboard players set .arrow_potion_id const 16
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_leaping"} run scoreboard players set .arrow_potion_id const 17
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_leaping"} run scoreboard players set .arrow_potion_id const 18
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:luck"} run scoreboard players set .arrow_potion_id const 19
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:regeneration"} run scoreboard players set .arrow_potion_id const 20
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_regeneration"} run scoreboard players set .arrow_potion_id const 21
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_regeneration"} run scoreboard players set .arrow_potion_id const 22
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:poison"} run scoreboard players set .arrow_potion_id const 23
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_poison"} run scoreboard players set .arrow_potion_id const 24
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_poison"} run scoreboard players set .arrow_potion_id const 25
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:fire_resistance"} run scoreboard players set .arrow_potion_id const 26
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_fire_resistance"} run scoreboard players set .arrow_potion_id const 27
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:water_breathing"} run scoreboard players set .arrow_potion_id const 28
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_water_breathing"} run scoreboard players set .arrow_potion_id const 29
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:night_vision"} run scoreboard players set .arrow_potion_id const 30
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_night_vision"} run scoreboard players set .arrow_potion_id const 31
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:invisibility"} run scoreboard players set .arrow_potion_id const 32
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_invisibility"} run scoreboard players set .arrow_potion_id const 33
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:turtle_master"} run scoreboard players set .arrow_potion_id const 34
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_turtle_master"} run scoreboard players set .arrow_potion_id const 35
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_turtle_master"} run scoreboard players set .arrow_potion_id const 36
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:slow_falling"} run scoreboard players set .arrow_potion_id const 37
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_slow_falling"} run scoreboard players set .arrow_potion_id const 38
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:wind_charged"} run scoreboard players set .arrow_potion_id const 39
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:oozing"} run scoreboard players set .arrow_potion_id const 40
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:infested"} run scoreboard players set .arrow_potion_id const 41
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:weaving"} run scoreboard players set .arrow_potion_id const 42
