execute if entity @s[type=minecraft:spectral_arrow] run scoreboard players set @s arrow_potion_id 0
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:swiftness"} run scoreboard players set @s arrow_potion_id 1
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_swiftness"} run scoreboard players set @s arrow_potion_id 2
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_swiftness"} run scoreboard players set @s arrow_potion_id 3
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:slowness"} run scoreboard players set @s arrow_potion_id 4
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_slowness"} run scoreboard players set @s arrow_potion_id 5
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_slowness"} run scoreboard players set @s arrow_potion_id 6
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strength"} run scoreboard players set @s arrow_potion_id 7
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_strength"} run scoreboard players set @s arrow_potion_id 8
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_strength"} run scoreboard players set @s arrow_potion_id 9
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:weakness"} run scoreboard players set @s arrow_potion_id 10
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_weakness"} run scoreboard players set @s arrow_potion_id 11
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:healing"} run scoreboard players set @s arrow_potion_id 12
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_healing"} run scoreboard players set @s arrow_potion_id 13
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:harming"} run scoreboard players set @s arrow_potion_id 14
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_harming"} run scoreboard players set @s arrow_potion_id 15
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:leaping"} run scoreboard players set @s arrow_potion_id 16
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_leaping"} run scoreboard players set @s arrow_potion_id 17
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_leaping"} run scoreboard players set @s arrow_potion_id 18
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:luck"} run scoreboard players set @s arrow_potion_id 19
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:regeneration"} run scoreboard players set @s arrow_potion_id 20
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_regeneration"} run scoreboard players set @s arrow_potion_id 21
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_regeneration"} run scoreboard players set @s arrow_potion_id 22
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:poison"} run scoreboard players set @s arrow_potion_id 23
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_poison"} run scoreboard players set @s arrow_potion_id 24
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_poison"} run scoreboard players set @s arrow_potion_id 25
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:fire_resistance"} run scoreboard players set @s arrow_potion_id 26
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_fire_resistance"} run scoreboard players set @s arrow_potion_id 27
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:water_breathing"} run scoreboard players set @s arrow_potion_id 28
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_water_breathing"} run scoreboard players set @s arrow_potion_id 29
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:night_vision"} run scoreboard players set @s arrow_potion_id 30
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_night_vision"} run scoreboard players set @s arrow_potion_id 31
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:invisibility"} run scoreboard players set @s arrow_potion_id 32
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_invisibility"} run scoreboard players set @s arrow_potion_id 33
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:turtle_master"} run scoreboard players set @s arrow_potion_id 34
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:strong_turtle_master"} run scoreboard players set @s arrow_potion_id 35
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_turtle_master"} run scoreboard players set @s arrow_potion_id 36
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:slow_falling"} run scoreboard players set @s arrow_potion_id 37
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:long_slow_falling"} run scoreboard players set @s arrow_potion_id 38
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:wind_charged"} run scoreboard players set @s arrow_potion_id 39
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:oozing"} run scoreboard players set @s arrow_potion_id 40
execute if data entity @s item.components.minecraft:potion_contents{potion:"minecraft:infested"} run scoreboard players set @s arrow_potion_id 41
