scoreboard objectives add entityid dummy
scoreboard objectives add entityid.0 dummy
scoreboard objectives add entityid.1 dummy
scoreboard objectives add entityid.2 dummy
scoreboard objectives add entityid.3 dummy
scoreboard objectives add entityid.4 dummy
scoreboard objectives add entityid.5 dummy
scoreboard objectives add entityid.6 dummy
scoreboard objectives add entityid.7 dummy
scoreboard objectives add entityid.8 dummy
scoreboard objectives add entityid.9 dummy
scoreboard objectives add entityid.10 dummy
scoreboard objectives add entityid.11 dummy
scoreboard objectives add entityid.12 dummy
scoreboard objectives add entityid.13 dummy
scoreboard objectives add entityid.14 dummy
scoreboard objectives add entityid.15 dummy
scoreboard objectives add entityid.16 dummy
scoreboard objectives add entityid.17 dummy
scoreboard objectives add entityid.18 dummy
scoreboard objectives add entityid.19 dummy
scoreboard objectives add entityid.20 dummy
scoreboard objectives add entityid.21 dummy
scoreboard objectives add entityid.22 dummy
scoreboard objectives add entityid.23 dummy
scoreboard objectives add entityid.24 dummy
scoreboard objectives add entityid.25 dummy
scoreboard objectives add entityid.26 dummy
scoreboard objectives add entityid.27 dummy
scoreboard objectives add entityid.28 dummy
scoreboard objectives add entityid.29 dummy
scoreboard objectives add entityid.30 dummy
scoreboard objectives add entityid.31 dummy
scoreboard players set #loaded entityid 1
scoreboard objectives add const dummy
scoreboard players set 2 const 2
scoreboard players set -1 const -1
scoreboard objectives add id dummy
scoreboard objectives add itemid dummy
scoreboard objectives add itemid_stored dummy
scoreboard objectives add reforgeId dummy
scoreboard objectives add interaction dummy
scoreboard objectives add attackinteraction dummy
scoreboard objectives add heal dummy
scoreboard objectives add cooldown dummy
scoreboard objectives add damage_dealt minecraft.custom:minecraft.damage_dealt
scoreboard objectives add stun dummy
scoreboard objectives add breaching dummy
scoreboard objectives add leeching dummy
scoreboard objectives add raging_melee dummy
scoreboard objectives add rage_meter_melee dummy
scoreboard objectives add forge_count dummy
scoreboard objectives add raging_tool dummy
scoreboard objectives add rage_meter_tool dummy
scoreboard objectives add timer_second dummy
scoreboard objectives add shielding_charges dummy
scoreboard objectives add max_shielding_charges dummy
scoreboard objectives add shielding_cooldown dummy
scoreboard objectives add supervision dummy
scoreboard objectives add sneaking minecraft.custom:minecraft.sneak_time
scoreboard objectives add health dummy
scoreboard objectives add init_health dummy
scoreboard objectives add drop_count dummy
scoreboard objectives add damage dummy
scoreboard objectives add death_count deathCount
scoreboard objectives add sprint_distance minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add sprint_cd dummy
scoreboard objectives add dashing_amount dummy
scoreboard objectives add max_dash_amount dummy
scoreboard objectives add dashing_count dummy
scoreboard objectives add mysterious_cd dummy
scoreboard objectives add mysterious_count dummy
scoreboard objectives add mythic_count dummy
scoreboard objectives add assassin_cd dummy
scoreboard objectives add warrior_cd dummy
scoreboard objectives add warrior_hit dummy
scoreboard objectives add warrior_count dummy
scoreboard objectives add healthful_count dummy
scoreboard objectives add healthful_cd dummy
scoreboard objectives add rapid_cd dummy
scoreboard objectives add rapid_count dummy
scoreboard objectives add arrow_type dummy
scoreboard objectives add arrow_id dummy
scoreboard objectives add sel.slot dummy
scoreboard objectives add last.slot dummy
scoreboard objectives add supervision_count dummy
scoreboard objectives add sneaky_count dummy
scoreboard objectives add self_repairing dummy
execute as @a at @s unless score @s last.slot matches 0.. run scoreboard players set @s last.slot 0
function find_looking:internal/load
scoreboard objectives add ability_cd1 dummy
scoreboard objectives add ability_cd2 dummy
scoreboard objectives add ability_cd3 dummy
scoreboard objectives add ability_action_cd1 dummy
scoreboard objectives add ability_action_cd2 dummy
scoreboard objectives add ability_action_cd3 dummy
scoreboard objectives add ability_health_remain dummy
scoreboard objectives add projectile_speed_digit dummy
scoreboard objectives add projectile_speed_demical dummy
scoreboard objectives add projectile_damage dummy
scoreboard objectives add projectile_ispiercing dummy
scoreboard objectives add projectile_aoe dummy
scoreboard objectives add projectile_contact_range_digit dummy
scoreboard objectives add projectile_contact_range_demical dummy
scoreboard objectives add projectile_duration dummy
scoreboard objectives add projectile_source_id dummy
scoreboard objectives add projectile_type dummy
scoreboard objectives add bullet_count dummy
scoreboard objectives add angry_at_id dummy
scoreboard objectives add absorption_store dummy
scoreboard objectives add absorption_amount dummy
scoreboard objectives add rampaging_attack dummy
scoreboard objectives add rampaging_cd dummy
scoreboard objectives add absorption_sword_cd dummy
scoreboard objectives add super_chainmail_count dummy
scoreboard objectives add absorption_armor_count dummy
scoreboard objectives add absorption_armor_cd dummy
scoreboard objectives add inferno_armor_count dummy
scoreboard objectives add berserk_armor_count dummy
scoreboard objectives add berserk_armor_cd dummy
scoreboard objectives add berserk_armor_kill_count dummy
scoreboard objectives add contagion_armor_count dummy
scoreboard objectives add reflective_armor_count dummy
scoreboard objectives add poisoned_armor_count dummy
scoreboard objectives add poison_bow_cd dummy
scoreboard objectives add poison_bow_tick dummy
scoreboard objectives add forest_count dummy
scoreboard objectives add super_tank_count dummy
scoreboard objectives add fire dummy
scoreboard objectives add arrow_potion_id dummy
scoreboard objectives add use dummy
scoreboard objectives add type dummy
scoreboard objectives add leave_game minecraft.custom:minecraft.leave_game
scoreboard players set @a leave_game 0
execute as @a at @s if score @s id matches 0.. run function reforge:unlock_all_reforges
execute unless score .ismobmodification const matches 0.. run scoreboard players set .ismobmodification const 0
execute unless score .isrequireconvert const matches 0.. run scoreboard players set .isrequireconvert const 0
execute unless score .istexturearmor const matches 0.. run scoreboard players set .istexturearmor const 1
execute unless score .forgecraft_loaded const matches 0.. run tellraw @a [{"color":"dark_gray","italic":false,"text":"--------------------"},{"bold":true,"color":"gold","italic":false,"text":"ForgeCraft"},{"bold":false,"color":"dark_gray","italic":false,"text":"--------------------\n\n"},{"bold":false,"color":"white","italic":false,"text":"Made by "},{"bold":true,"color":"aqua","italic":false,"text":"LPMC2\n"},{"color":"red","text":"\nWarning: This datapack requires resource pack to work.\n(Or else armor texture will be MISSING!)\n"},{"bold":false,"color":"light_purple","italic":false,"text":"To get the resource pack, "},{"bold":false,"click_event":{"action":"open_url","url":"https://www.curseforge.com/minecraft/texture-packs/forgecraft-support-resource-pack"},"color":"white","italic":false,"text":"download it here: https://www.curseforge.com/minecraft/texture-packs/forgecraft-support-resource-pack"},{"bold":true,"color":"white","italic":false,"text":"\n\nSettings:\n"},{"bold":false,"click_event":{"action":"run_command","command":"function gamerules:ismobmodification/set"},"color":"light_purple","hover_event":{"action":"show_text","value":[{"text":"Set if the mob will have special condition to spawn.","color":"white","italic":false}]},"italic":false,"text":"[Set Mod Modification]"},{"bold":false,"click_event":{"action":"run_command","command":"function gamerules:isrequireconvert/set"},"color":"light_purple","hover_event":{"action":"show_text","value":[{"text":"Set if the item requires Forging Convert to forge the item.","color":"white","italic":false}]},"italic":false,"text":"\n[Set Require Convert]"},{"bold":false,"click_event":{"action":"run_command","command":"function gamerules:istexturearmor/set"},"color":"light_purple","hover_event":{"action":"show_text","value":[{"text":"Set if the armor item will provide texture. (This prevents the item to have invisible armor texture)","color":"white","italic":false}]},"italic":false,"text":"\n[Set Armor Texture]"},{"bold":false,"color":"dark_gray","italic":false,"text":"\n\n----------------------------------------"}]
execute unless score .forgecraft_loaded const matches 0.. run scoreboard players set .forgecraft_loaded const 1