scoreboard objectives add raging_melee
scoreboard objectives add rage_meter_melee
scoreboard objectives add forge_count
scoreboard objectives add raging_tool
scoreboard objectives add rage_meter_tool
scoreboard objectives add timer_second
scoreboard objectives add shielding_charges
scoreboard objectives add max_shielding_charges
scoreboard objectives add shielding_cooldown
scoreboard objectives add supervision
scoreboard objectives add sneaking minecraft.custom:minecraft.sneak_time
scoreboard objectives add health
scoreboard objectives add init_health
scoreboard objectives add drop_count
scoreboard objectives add damage
scoreboard objectives add death_count deathCount
scoreboard objectives add sprint_distance minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add sprint_cd
scoreboard objectives add dashing_amount
scoreboard objectives add max_dash_amount
scoreboard objectives add dashing_count
scoreboard objectives add mysterious_cd
scoreboard objectives add mysterious_count
scoreboard objectives add mythic_count
scoreboard objectives add assassin_cd
scoreboard objectives add warrior_cd
scoreboard objectives add warrior_hit
scoreboard objectives add warrior_count
scoreboard objectives add healthful_count
scoreboard objectives add healthful_cd
scoreboard objectives add rapid_cd
scoreboard objectives add rapid_count
scoreboard objectives add arrow_type
scoreboard objectives add arrow_id
scoreboard objectives add sel.slot
scoreboard objectives add last.slot
scoreboard objectives add supervision_count
scoreboard objectives add sneaky_count
scoreboard objectives add self_repairing
execute as @a at @s unless score @s last.slot matches 0.. run scoreboard players set @s last.slot 0
#function find_looking:internal/load
scoreboard objectives add ability_cd1
scoreboard objectives add ability_cd2
scoreboard objectives add ability_cd3
scoreboard objectives add ability_action_cd1
scoreboard objectives add ability_action_cd2
scoreboard objectives add ability_action_cd3
scoreboard objectives add ability_health_remain
scoreboard objectives add bullet_count
scoreboard objectives add angry_at_id
scoreboard objectives add absorption_store
scoreboard objectives add absorption_amount
scoreboard objectives add rampaging_attack
scoreboard objectives add rampaging_cd
scoreboard objectives add absorption_sword_cd
scoreboard objectives add super_chainmail_count
scoreboard objectives add absorption_armor_count
scoreboard objectives add absorption_armor_cd
scoreboard objectives add inferno_armor_count
scoreboard objectives add berserk_armor_count
scoreboard objectives add berserk_armor_cd
scoreboard objectives add berserk_armor_kill_count
scoreboard objectives add contagion_armor_count
scoreboard objectives add reflective_armor_count
scoreboard objectives add poisoned_armor_count
scoreboard objectives add poison_bow_cd
scoreboard objectives add poison_bow_tick
scoreboard objectives add forest_count
scoreboard objectives add super_tank_count
scoreboard objectives add midas_forge_armor_count
scoreboard objectives add midas_converted
scoreboard objectives add breezy_reforge_cd
scoreboard objectives add electric_reforge_cd