execute if score .item_reforge reforgeId matches 0 run scoreboard players set .req_xp const 0
execute if score .item_reforge reforgeId matches 1 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 2 run scoreboard players set .req_xp const 9
execute if score .item_reforge reforgeId matches 3 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 4 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 5 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 6 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 7 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 8 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 9 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 10 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 11 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 12 run scoreboard players set .req_xp const 20
execute if score .item_reforge reforgeId matches 13 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 14 run scoreboard players set .req_xp const 40
execute if score .item_reforge reforgeId matches 15 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 16 run scoreboard players set .req_xp const 20
execute if score .item_reforge reforgeId matches 17 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 18 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 19 run scoreboard players set .req_xp const 50
execute if score .item_reforge reforgeId matches 20 run scoreboard players set .req_xp const 25
execute if score .item_reforge reforgeId matches 21 run scoreboard players set .req_xp const 25
execute if score .item_reforge reforgeId matches 22 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 23 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 24 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 25 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 26 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 27 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 28 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 29 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 30 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 31 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 32 run scoreboard players set .req_xp const 32
execute if score .item_reforge reforgeId matches 33 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 34 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 35 run scoreboard players set .req_xp const 1
execute if score .item_reforge reforgeId matches 36 run scoreboard players set .req_xp const 20
execute if score .item_reforge reforgeId matches 37 run scoreboard players set .req_xp const 25
execute if score .item_reforge reforgeId matches 38 run scoreboard players set .req_xp const 30
execute if score .item_reforge reforgeId matches 39 run scoreboard players set .req_xp const 3
execute if score .item_reforge reforgeId matches 40 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 41 run scoreboard players set .req_xp const 1
execute if score .item_reforge reforgeId matches 42 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 43 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 44 run scoreboard players set .req_xp const 20
execute if score .item_reforge reforgeId matches 45 run scoreboard players set .req_xp const 12
execute if score .item_reforge reforgeId matches 46 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 47 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 48 run scoreboard players set .req_xp const 25
execute if score .item_reforge reforgeId matches 49 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 50 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 51 run scoreboard players set .req_xp const 30
execute if score .item_reforge reforgeId matches 52 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 53 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 54 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 55 run scoreboard players set .req_xp const 18
execute if score .item_reforge reforgeId matches 56 run scoreboard players set .req_xp const 1
execute if score .item_reforge reforgeId matches 57 run scoreboard players set .req_xp const 25
execute if score .item_reforge reforgeId matches 58 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 59 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 60 run scoreboard players set .req_xp const 6
execute if score .item_reforge reforgeId matches 61 run scoreboard players set .req_xp const 30
execute if score .item_reforge reforgeId matches 62 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 63 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 64 run scoreboard players set .req_xp const 30
execute if score .item_reforge reforgeId matches 65 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 66 run scoreboard players set .req_xp const 40
execute if score .item_reforge reforgeId matches 67 run scoreboard players set .req_xp const 15
execute if score .item_reforge reforgeId matches 68 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 69 run scoreboard players set .req_xp const 1
execute if score .item_reforge reforgeId matches 70 run scoreboard players set .req_xp const 30
execute if score .item_reforge reforgeId matches 71 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 72 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 73 run scoreboard players set .req_xp const 17
execute if score .item_reforge reforgeId matches 74 run scoreboard players set .req_xp const 8
execute if score .item_reforge reforgeId matches 75 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 76 run scoreboard players set .req_xp const 20
execute if score .item_reforge reforgeId matches 77 run scoreboard players set .req_xp const 5
execute if score .item_reforge reforgeId matches 78 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 79 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 80 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 81 run scoreboard players set .req_xp const 10
execute if score .item_reforge reforgeId matches 82 run scoreboard players set .req_xp const 1
execute if score .item_reforge reforgeId matches 83 run scoreboard players set .req_xp const 50
# execute if score .item_reforge reforgeId matches 84 run scoreboard players set .req_xp const 0
execute if score .item_reforge reforgeId matches 85 run scoreboard players set .req_xp const 0
execute if score .item_reforge reforgeId matches 86 run scoreboard players set .req_xp const 50
execute store result entity @n[type=item_display,tag=targetforgemodifier] item.components.minecraft:custom_data.req_xp int 1 run scoreboard players operation .apply_cost const = .req_xp const