execute if score $temp_entityid.0 const matches 0 run tag @s add entityhit.nbit0
execute if score $temp_entityid.0 const matches 1 run tag @s add entityhit.bit0
execute if score $temp_entityid.1 const matches 0 run tag @s add entityhit.nbit1
execute if score $temp_entityid.1 const matches 1 run tag @s add entityhit.bit1
execute if score $temp_entityid.2 const matches 0 run tag @s add entityhit.nbit2
execute if score $temp_entityid.2 const matches 1 run tag @s add entityhit.bit2
execute if score $temp_entityid.3 const matches 0 run tag @s add entityhit.nbit3
execute if score $temp_entityid.3 const matches 1 run tag @s add entityhit.bit3
execute if score $temp_entityid.4 const matches 0 run tag @s add entityhit.nbit4
execute if score $temp_entityid.4 const matches 1 run tag @s add entityhit.bit4
execute if score $temp_entityid.5 const matches 0 run tag @s add entityhit.nbit5
execute if score $temp_entityid.5 const matches 1 run tag @s add entityhit.bit5
execute if score $temp_entityid.6 const matches 0 run tag @s add entityhit.nbit6
execute if score $temp_entityid.6 const matches 1 run tag @s add entityhit.bit6
execute if score $temp_entityid.7 const matches 0 run tag @s add entityhit.nbit7
execute if score $temp_entityid.7 const matches 1 run tag @s add entityhit.bit7
execute if score $temp_entityid.8 const matches 0 run tag @s add entityhit.nbit8
execute if score $temp_entityid.8 const matches 1 run tag @s add entityhit.bit8
execute if score $temp_entityid.9 const matches 0 run tag @s add entityhit.nbit9
execute if score $temp_entityid.9 const matches 1 run tag @s add entityhit.bit9
execute if score $temp_entityid.10 const matches 0 run tag @s add entityhit.nbit10
execute if score $temp_entityid.10 const matches 1 run tag @s add entityhit.bit10
execute if score $temp_entityid.11 const matches 0 run tag @s add entityhit.nbit11
execute if score $temp_entityid.11 const matches 1 run tag @s add entityhit.bit11
execute if score $temp_entityid.12 const matches 0 run tag @s add entityhit.nbit12
execute if score $temp_entityid.12 const matches 1 run tag @s add entityhit.bit12
execute if score $temp_entityid.13 const matches 0 run tag @s add entityhit.nbit13
execute if score $temp_entityid.13 const matches 1 run tag @s add entityhit.bit13
execute if score $temp_entityid.14 const matches 0 run tag @s add entityhit.nbit14
execute if score $temp_entityid.14 const matches 1 run tag @s add entityhit.bit14
execute if score $temp_entityid.15 const matches 0 run tag @s add entityhit.nbit15
execute if score $temp_entityid.15 const matches 1 run tag @s add entityhit.bit15
execute if score $temp_entityid.16 const matches 0 run tag @s add entityhit.nbit16
execute if score $temp_entityid.16 const matches 1 run tag @s add entityhit.bit16
execute if score $temp_entityid.17 const matches 0 run tag @s add entityhit.nbit17
execute if score $temp_entityid.17 const matches 1 run tag @s add entityhit.bit17
execute if score $temp_entityid.18 const matches 0 run tag @s add entityhit.nbit18
execute if score $temp_entityid.18 const matches 1 run tag @s add entityhit.bit18
execute if score $temp_entityid.19 const matches 0 run tag @s add entityhit.nbit19
execute if score $temp_entityid.19 const matches 1 run tag @s add entityhit.bit19
execute if score $temp_entityid.20 const matches 0 run tag @s add entityhit.nbit20
execute if score $temp_entityid.20 const matches 1 run tag @s add entityhit.bit20
execute if score $temp_entityid.21 const matches 0 run tag @s add entityhit.nbit21
execute if score $temp_entityid.21 const matches 1 run tag @s add entityhit.bit21
execute if score $temp_entityid.22 const matches 0 run tag @s add entityhit.nbit22
execute if score $temp_entityid.22 const matches 1 run tag @s add entityhit.bit22
execute if score $temp_entityid.23 const matches 0 run tag @s add entityhit.nbit23
execute if score $temp_entityid.23 const matches 1 run tag @s add entityhit.bit23
execute if score $temp_entityid.24 const matches 0 run tag @s add entityhit.nbit24
execute if score $temp_entityid.24 const matches 1 run tag @s add entityhit.bit24
execute if score $temp_entityid.25 const matches 0 run tag @s add entityhit.nbit25
execute if score $temp_entityid.25 const matches 1 run tag @s add entityhit.bit25
execute if score $temp_entityid.26 const matches 0 run tag @s add entityhit.nbit26
execute if score $temp_entityid.26 const matches 1 run tag @s add entityhit.bit26
execute if score $temp_entityid.27 const matches 0 run tag @s add entityhit.nbit27
execute if score $temp_entityid.27 const matches 1 run tag @s add entityhit.bit27
execute if score $temp_entityid.28 const matches 0 run tag @s add entityhit.nbit28
execute if score $temp_entityid.28 const matches 1 run tag @s add entityhit.bit28
execute if score $temp_entityid.29 const matches 0 run tag @s add entityhit.nbit29
execute if score $temp_entityid.29 const matches 1 run tag @s add entityhit.bit29
execute if score $temp_entityid.30 const matches 0 run tag @s add entityhit.nbit30
execute if score $temp_entityid.30 const matches 1 run tag @s add entityhit.bit30
execute if score $temp_entityid.31 const matches 0 run tag @s add entityhit.nbit31
execute if score $temp_entityid.31 const matches 1 run tag @s add entityhit.bit31
execute as @s run function entity_hit_matching:reset