scoreboard players reset @s entityid.0
scoreboard players reset @s entityid.1
scoreboard players reset @s entityid.2
scoreboard players reset @s entityid.3
scoreboard players reset @s entityid.4
scoreboard players reset @s entityid.5
scoreboard players reset @s entityid.6
scoreboard players reset @s entityid.7
scoreboard players reset @s entityid.8
scoreboard players reset @s entityid.9
scoreboard players reset @s entityid.10
scoreboard players reset @s entityid.11
scoreboard players reset @s entityid.12
scoreboard players reset @s entityid.13
scoreboard players reset @s entityid.14
scoreboard players reset @s entityid.15
scoreboard players reset @s entityid.16
scoreboard players reset @s entityid.17
scoreboard players reset @s entityid.18
scoreboard players reset @s entityid.19
scoreboard players reset @s entityid.20
scoreboard players reset @s entityid.21
scoreboard players reset @s entityid.22
scoreboard players reset @s entityid.23
scoreboard players reset @s entityid.24
scoreboard players reset @s entityid.25
scoreboard players reset @s entityid.26
scoreboard players reset @s entityid.27
scoreboard players reset @s entityid.28
scoreboard players reset @s entityid.29
scoreboard players reset @s entityid.30
scoreboard players reset @s entityid.31