scoreboard players reset $temp entityid.0
scoreboard players reset $temp entityid.1
scoreboard players reset $temp entityid.2
scoreboard players reset $temp entityid.3
scoreboard players reset $temp entityid.4
scoreboard players reset $temp entityid.5
scoreboard players reset $temp entityid.6
scoreboard players reset $temp entityid.7
scoreboard players reset $temp entityid.8
scoreboard players reset $temp entityid.9
scoreboard players reset $temp entityid.10
scoreboard players reset $temp entityid.11
scoreboard players reset $temp entityid.12
scoreboard players reset $temp entityid.13
scoreboard players reset $temp entityid.14
scoreboard players reset $temp entityid.15
scoreboard players reset $temp entityid.16
scoreboard players reset $temp entityid.17
scoreboard players reset $temp entityid.18
scoreboard players reset $temp entityid.19
scoreboard players reset $temp entityid.20
scoreboard players reset $temp entityid.21
scoreboard players reset $temp entityid.22
scoreboard players reset $temp entityid.23
scoreboard players reset $temp entityid.24
scoreboard players reset $temp entityid.25
scoreboard players reset $temp entityid.26
scoreboard players reset $temp entityid.27
scoreboard players reset $temp entityid.28
scoreboard players reset $temp entityid.29
scoreboard players reset $temp entityid.30
scoreboard players reset $temp entityid.31