scoreboard players reset $temp_entityid.0 const
scoreboard players reset $temp_entityid.1 const
scoreboard players reset $temp_entityid.2 const
scoreboard players reset $temp_entityid.3 const
scoreboard players reset $temp_entityid.4 const
scoreboard players reset $temp_entityid.5 const
scoreboard players reset $temp_entityid.6 const
scoreboard players reset $temp_entityid.7 const
scoreboard players reset $temp_entityid.8 const
scoreboard players reset $temp_entityid.9 const
scoreboard players reset $temp_entityid.10 const
scoreboard players reset $temp_entityid.11 const
scoreboard players reset $temp_entityid.12 const
scoreboard players reset $temp_entityid.13 const
scoreboard players reset $temp_entityid.14 const
scoreboard players reset $temp_entityid.15 const
scoreboard players reset $temp_entityid.16 const
scoreboard players reset $temp_entityid.17 const
scoreboard players reset $temp_entityid.18 const
scoreboard players reset $temp_entityid.19 const
scoreboard players reset $temp_entityid.20 const
scoreboard players reset $temp_entityid.21 const
scoreboard players reset $temp_entityid.22 const
scoreboard players reset $temp_entityid.23 const
scoreboard players reset $temp_entityid.24 const
scoreboard players reset $temp_entityid.25 const
scoreboard players reset $temp_entityid.26 const
scoreboard players reset $temp_entityid.27 const
scoreboard players reset $temp_entityid.28 const
scoreboard players reset $temp_entityid.29 const
scoreboard players reset $temp_entityid.30 const
scoreboard players reset $temp_entityid.31 const