recipe give @s crafting:reforge_anvil
recipe give @s crafting:armor_polisher
recipe give @s crafting:auto_repair_toolkit
recipe give @s crafting:axe_to_tool
recipe give @s crafting:block_of_volts
recipe give @s crafting:book_of_magic
recipe give @s crafting:bunch_of_feathers
recipe give @s crafting:core_of_indestructible
recipe give @s crafting:crystalized_cactus
recipe give @s crafting:dark_orb
recipe give @s crafting:drill_engine
recipe give @s crafting:efficient_reforge
recipe give @s crafting:emerald_relic
recipe give @s crafting:energy_orb
recipe give @s crafting:experienced_reforge
recipe give @s crafting:farmer_block
recipe give @s crafting:fortune_of_mining
recipe give @s crafting:gold_core
recipe give @s crafting:heart_of_the_jungle
recipe give @s crafting:heat_core
recipe give @s crafting:hermes_boots
recipe give @s crafting:invisibility_cauldron
recipe give @s crafting:leaflet_gem
recipe give @s crafting:magic_core
recipe give @s crafting:magical_blackstone_shield
recipe give @s crafting:mini_grindstone
recipe give @s crafting:mysterious_ice_in_a_glass
recipe give @s crafting:mysterious_mushroom
recipe give @s crafting:netherite_scrap_pile
recipe give @s crafting:orb_of_stun
recipe give @s crafting:ornate_stone
recipe give @s crafting:potion_of_weakening
recipe give @s crafting:power_core
recipe give @s crafting:reinforced_clipped_wings
recipe give @s crafting:repair_toolkit
recipe give @s crafting:rune_of_aggro
recipe give @s crafting:rusty_anvil
recipe give @s crafting:sculk_gem
recipe give @s crafting:sharp_metal_necklace
recipe give @s crafting:speedy_block
recipe give @s crafting:tanky_reforge
recipe give @s crafting:unused_scope
recipe give @s crafting:vanilla_item_converter
recipe give @s crafting:vanilla_item_converter_2
recipe give @s crafting:weapon_extender
recipe give @s crafting:weapon_sharpener
recipe give @s crafting:weaponized_reforge
recipe give @s crafting:powerful_reforge
recipe give @s crafting:diver_reforge
recipe give @s crafting:durable_reforge
recipe give @s crafting:orb_of_rage
recipe give @s crafting:supervision_reforge
recipe give @s crafting:iron_blade
recipe give @s crafting:water_gem
recipe give @s crafting:leaping_reforge
recipe give @s crafting:tactical_reforge
recipe give @s crafting:fortified_reforge
recipe give @s crafting:reflective_reforge
recipe give @s crafting:inferno_reforge
recipe give @s crafting:absorptive_reforge
recipe give @s crafting:rampaging_reforge
recipe give @s crafting:swarming_reforge
recipe give @s crafting:enhanced_reforge
recipe give @s crafting:runic_reforge
recipe give @s crafting:ender_reforge
recipe give @s crafting:diamond_dispenser
recipe give @s crafting:agile_reforge
recipe give @s crafting:rotten_reforge
recipe give @s crafting:defending_reforge
recipe give @s crafting:book_of_armor
recipe give @s crafting:book_of_armor_toughness
recipe give @s crafting:book_of_attack_speed
recipe give @s crafting:book_of_block_reaching
recipe give @s crafting:book_of_burning_time
recipe give @s crafting:book_of_damage
recipe give @s crafting:book_of_falling
recipe give @s crafting:book_of_gravity
recipe give @s crafting:book_of_health
recipe give @s crafting:book_of_knockback
recipe give @s crafting:book_of_knockback_resistance
recipe give @s crafting:book_of_leaping
recipe give @s crafting:book_of_mining_speed
recipe give @s crafting:book_of_mob_reaching
recipe give @s crafting:book_of_shrunking
recipe give @s crafting:book_of_speed
recipe give @s crafting:book_of_water_breathing
recipe give @s crafting:book_of_giant
recipe give @s crafting:poisoned_reforge
recipe give @s crafting:guardian_reforge
recipe give @s crafting:cursed_reforge
recipe give @s crafting:leeching_reforge
recipe give @s crafting:electric_reforge
recipe give @s crafting:scavenger_reforge
recipe give @s crafting:chaining_reforge
recipe give @s crafting:copperize_reforge
recipe give @s crafting:supreme_reforge