recipe give @s crafting:reforge_anvil
recipe give @s crafting:axe_to_tool
recipe give @s crafting:heat_core
recipe give @s crafting:leaflet_gem
recipe give @s crafting:reinforced_clipped_wings
recipe give @s crafting:repair_toolkit
recipe give @s crafting:rusty_anvil
recipe give @s crafting:tanky_reforge
recipe give @s crafting:vanilla_item_converter
recipe give @s crafting:diver_reforge
recipe give @s crafting:durable_reforge
recipe give @s crafting:mysterious_ice_in_a_glass
recipe give @s crafting:copperize_reforge
recipe give @s crafting:enchanting_reforge
recipe give @s crafting:deforger_converter
recipe give @s crafting:scavenger_reforge