recipe give @s crafting:book_of_armor
recipe give @s crafting:book_of_armor_toughness
recipe give @s crafting:book_of_attack_speed
recipe give @s crafting:book_of_block_reaching
recipe give @s crafting:book_of_burning_time
recipe give @s crafting:book_of_damage
recipe give @s crafting:book_of_falling
recipe give @s crafting:book_of_giant
recipe give @s crafting:book_of_gravity
recipe give @s crafting:book_of_health
recipe give @s crafting:book_of_knockback
recipe give @s crafting:book_of_knockback_resistance
recipe give @s crafting:book_of_leaping
recipe give @s crafting:book_of_mining_speed
recipe give @s crafting:book_of_mob_reaching
recipe give @s crafting:book_of_shrunking
recipe give @s crafting:book_of_speed
recipe give @s crafting:book_of_water_breathing