execute if score .item_mod id matches 1 run function reforge:forging/forge_type/enhancement/type/armor_toughness with storage minecraft:reforge forge
execute if score .item_mod id matches 2 run function reforge:forging/forge_type/enhancement/type/armor with storage minecraft:reforge forge
execute if score .item_mod id matches 3 run function reforge:forging/forge_type/enhancement/type/attack_speed with storage minecraft:reforge forge
execute if score .item_mod id matches 4 run function reforge:forging/forge_type/enhancement/type/block_reaching with storage minecraft:reforge forge
execute if score .item_mod id matches 5 run function reforge:forging/forge_type/enhancement/type/burning_time with storage minecraft:reforge forge
execute if score .item_mod id matches 6 run function reforge:forging/forge_type/enhancement/type/attack_damage with storage minecraft:reforge forge
execute if score .item_mod id matches 7 run function reforge:forging/forge_type/enhancement/type/falling with storage minecraft:reforge forge
execute if score .item_mod id matches 8 run function reforge:forging/forge_type/enhancement/type/giant with storage minecraft:reforge forge
execute if score .item_mod id matches 9 run function reforge:forging/forge_type/enhancement/type/gravity with storage minecraft:reforge forge
execute if score .item_mod id matches 10 run function reforge:forging/forge_type/enhancement/type/max_health with storage minecraft:reforge forge
execute if score .item_mod id matches 11 run function reforge:forging/forge_type/enhancement/type/knockback_resistance with storage minecraft:reforge forge
execute if score .item_mod id matches 12 run function reforge:forging/forge_type/enhancement/type/knockback with storage minecraft:reforge forge
execute if score .item_mod id matches 13 run function reforge:forging/forge_type/enhancement/type/leaping with storage minecraft:reforge forge
execute if score .item_mod id matches 14 run function reforge:forging/forge_type/enhancement/type/mining_speed with storage minecraft:reforge forge
execute if score .item_mod id matches 15 run function reforge:forging/forge_type/enhancement/type/mob_reaching with storage minecraft:reforge forge
execute if score .item_mod id matches 16 run function reforge:forging/forge_type/enhancement/type/shrunking with storage minecraft:reforge forge
execute if score .item_mod id matches 17 run function reforge:forging/forge_type/enhancement/type/movement_speed with storage minecraft:reforge forge
execute if score .item_mod id matches 18 run function reforge:forging/forge_type/enhancement/type/water_breathing with storage minecraft:reforge forge