execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
execute as @s run summon guardian ~ ~ ~
